### ISSUE TITLE
报错了401 

### ISSUE THREAD

**Issue by kcoderk** [flytam/CsdnSyncHexo#12]
401 请登录后操作！

**Comment by flytam** [comment]
@kcoderk 最近csdn变更。。现在api接口已经不再通过cookie进行身份校验，改为token 头计算。最近我会切换为无需身份校验的纯爬虫版本

**Comment by flytam** [comment]
@kcoderk 我这边刚测试是正常的，cookie信息配置对了吗？

**Comment by yyguy123** [comment]
我这边试了也是一直报 401 请登录后操作！

**Comment by flytam** [comment]
@kcoderk @yyguy123 我尝试了下，csdn现在那个链接，登录状态下只能获取自己的文章了。所以你点开我的readme的链接报未登录是无所谓的，你再直接按照文档说明获取那个cookie就行了，现在只能批量获取自己的文章了。后续我会更新个纯爬虫的版本，不调用api，

**Comment by yyguy123** [comment]
我就是获取自己的也报这个401   难道是我cookie拷的不对？ 不是直接把cookie那一整串字符串copy么？ 
原谅我小白  不知道是不是操作不对

**Comment by flytam** [comment]
> 我就是获取自己的也报这个401 难道是我cookie拷的不对？ 不是直接把cookie那一整串字符串copy么？
> 原谅我小白 不知道是不是操作不对

@yyguy123 https://blog-console-api.csdn.net/v1/editor/getArticle?id=文章id 你在登陆状态下，点开这个链接的内容能看到么。文章id换成你自己的一篇文章的id

**Comment by yyguy123** [comment]
> > 我就是获取自己的也报这个401 难道是我cookie拷的不对？ 不是直接把cookie那一整串字符串copy么？
> > 原谅我小白 不知道是不是操作不对
> 
> @yyguy123 [https://blog-console-api.csdn.net/v1/editor/getArticle?id=文章id](https://blog-console-api.csdn.net/v1/editor/getArticle?id=%E6%96%87%E7%AB%A0id) 你在登陆状态下，点开这个链接的内容能看到么。文章id换成你自己的一篇文章的id

在登录状态下用这个连接换成我自己的文章id 有返回
![image](https://user-images.githubusercontent.com/41152248/80776297-a5204e80-8b94-11ea-9cb9-7ec0605364a1.png)
我用这个页面的cookie
![image](https://user-images.githubusercontent.com/41152248/80776359-cbde8500-8b94-11ea-960a-5d3fc9d039b9.png)
也没用
按照下面这样会报401
![image](https://user-images.githubusercontent.com/41152248/80776469-08aa7c00-8b95-11ea-8a76-2d841995e916.png)
如果csdn链接后面跟上详细的某一篇文章的id的话不会报401  但是就显示
![image](https://user-images.githubusercontent.com/41152248/80776548-38598400-8b95-11ea-93a5-324a3e3f98d4.png)
但是文件并没有生成

**Comment by flytam** [comment]
@yyguy123 非常抱歉。博客的文章字段手误了。配置文件应该是cookie而不是cookies。如果能生成成功的话....卑微的求一个star 2333

**Comment by yyguy123** [comment]
> @yyguy123 非常抱歉。博客的文章字段手误了。配置文件应该是cookie而不是cookies。如果能生成成功的话....卑微的求一个star 2333

已star    不过有的文章解析出的格式有点乱

**Comment by flytam** [comment]
生成成功了吗，哪些格式错乱的，截图下输出格式我看看呢，我看看能不能优化下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyguy <notifications@github.com&gt;
发送时间: 2020年5月1日 20:26
收件人: flytam/CsdnSyncHexo <CsdnSyncHexo@noreply.github.com&gt;
抄送: Flytam <tanjiahui2015@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[flytam/CsdnSyncHexo] 报错了401  (#12)

**Comment by yyguy123** [comment]
生成成功了    
![image](https://user-images.githubusercontent.com/41152248/80805500-d0ce2380-8bea-11ea-835e-71b8764a3c48.png)
生成后是这样的
![image](https://user-images.githubusercontent.com/41152248/80805557-f22f0f80-8bea-11ea-982a-3df07d302e2b.png)
本来都应该在块中，结果只有其中一部分被放入块中，中间还断开了，比如这种
![image](https://user-images.githubusercontent.com/41152248/80805625-20acea80-8beb-11ea-9e60-48a247c182f1.png)
整体来说还是好用的   有的文章出现这种情况不知道咋回事

**Comment by flytam** [comment]
感谢反馈，我看看

**Comment by flytam** [comment]
@yyguy123 已经更新一波，可以支持不传cookie的生成方式，这样就没有本人的文章的限制，就是不剩生成标签，可以用2.2.0版本尝试下，详情可见readme
