### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by godzeo** [flytam/CsdnSyncHexo#13]
![image](https://user-images.githubusercontent.com/64398024/80793664-5392b680-8bca-11ea-91e2-0feee7215a18.png)

**Comment by flytam** [comment]
@godzeo 应该是json格式不正确，执行的时候把配置文件的注释去掉，就是去掉我样例中的//。如果能用的话 卑微的求一个start 2333

**Comment by godzeo** [comment]
还是不行，是mac不兼容吗
![image](https://user-images.githubusercontent.com/64398024/80803548-328b8f00-8be5-11ea-889d-d3125585e423.png)
![image](https://user-images.githubusercontent.com/64398024/80803558-3a4b3380-8be5-11ea-8499-0b2643ea6e4a.png)


第二种既然没有这个参数。。
![image](https://user-images.githubusercontent.com/64398024/80803461-ec363000-8be4-11ea-8814-0a7e27b365eb.png)

**Comment by flytam** [comment]
@godzeo base字段，最后的,去掉

**Comment by flytam** [comment]
> 还是不行，是mac不兼容吗
> 
> ![image](https://user-images.githubusercontent.com/64398024/80803548-328b8f00-8be5-11ea-889d-d3125585e423.png)
> 
> ![image](https://user-images.githubusercontent.com/64398024/80803558-3a4b3380-8be5-11ea-8499-0b2643ea6e4a.png)
> 
> 
> 
> 
> 
> 第二种既然没有这个参数。。
> 
> ![image](https://user-images.githubusercontent.com/64398024/80803461-ec363000-8be4-11ea-8814-0a7e27b365eb.png)
> 
> 

base去掉这个参数应该去掉了。。我回头整理下文档

**Comment by godzeo** [comment]
可以了，确实格式有问题

**Comment by flytam** [comment]
@godzeo 我的锅，我把文档重新整理清楚

**Comment by flytam** [comment]
@godzeo  已经更新一波，可以支持不传cookie的生成方式，这样就没有本人的文章的限制，就是不剩生成标签，可以用2.2.0版本尝试下，详情可见readme
