### ISSUE TITLE
csdn的api更换了，并且新的api直接访问不返回结果

### ISSUE THREAD

**Issue by tangg555** [flytam/CsdnSyncHexo#14]
今天刚尝试了大佬的代码，发现不管是否提供cookie都运行不了：
![4G0LJFX8@PAK5LC CR346{I](https://user-images.githubusercontent.com/22412972/82631139-60ce1e80-9c27-11ea-87b9-b740df84af80.png)
我猜报错的原因应该是爬了个空气，所以我看了下发送的请求。发现这里的api域名跟项目README中不一样。
实际请求：
![16%NSSS9Q))J1WK5 Q{{P@3](https://user-images.githubusercontent.com/22412972/82631270-af7bb880-9c27-11ea-808c-b6ae1ca97cfc.png)
README中为：
https://blog-console-api.csdn.net/v1/editor/getArticle?id=xxxx

于是我用浏览器直接访问了实际的请求URL，但是无法访问：
![%TSSO4_0HL_U273I7346HRA](https://user-images.githubusercontent.com/22412972/82631392-e356de00-9c27-11ea-994d-7f31b9eb3d0d.png)

但用https://blog-console-api.csdn.net/v1/editor/getArticle?id=xxxx 访问时成功了，得到了json数据，但是json数据中没有mardowncontent:
![CCZ@(J%N8VR2I) 802G{V96](https://user-images.githubusercontent.com/22412972/82631452-0b464180-9c28-11ea-8784-88209e5cf193.png)

以上是我遇到的问题，顺便我还想问一下大佬用浏览器直接访问了实际的请求URL，无法访问是为什么？明明我直接编辑文章的时候监测到了这一个请求。

以上。

**Comment by flytam** [comment]
@tangg555 csdn好像加了点反爬策略，周末我更新修复下这里

**Comment by tangg555** [comment]
好的，谢谢。我要顺便学习下怎么反反爬:-)

**Comment by flytam** [comment]
@tangg555 npm i -g csdnsynchexo@latest 试下最新版看看？我这边测试可以了

**Comment by tangg555** [comment]
我测了一下，确实是生成了，不过内容是html的
![W7LHFM~W@ZR30 MU%B}YGX](https://user-images.githubusercontent.com/22412972/82651353-a3572180-9c4e-11ea-92c6-a55902f298a4.png)
![LRJQ12O)N}6P9`(FTO7)7ZJ](https://user-images.githubusercontent.com/22412972/82651387-ace08980-9c4e-11ea-813f-66a766a663c9.png)
我下午研究了一下，我发现就算我用google的F12查getArticle...那个请求，返回的json里面markdowncontent也是空的。

难道csdn现在给客户端只传html来渲染？或者它想办法把markdown的数据想别的办法传过来了？

**Comment by flytam** [comment]
@tangg555 如果你使用提供cookie的方式的话，文章本身是用富文本形式编写的话是拿不到markdown的。可以尝试下不使用cookie的形式，这种是直接爬页面的html转成markdown

**Comment by tangg555** [comment]
不使用cookie的话全都都报了一个错误：
![N2WALKO0VX}IOGNF(TNSH0I](https://user-images.githubusercontent.com/22412972/82652449-38a6e580-9c50-11ea-8736-ae452bde5119.png)

**Comment by flytam** [comment]
方便给下你要爬的csdn链接吗

**Comment by tangg555** [comment]
好的麻烦大佬了
https://blog.csdn.net/tangg555

**Comment by flytam** [comment]
用最新版本的可以了..之前代码里面写死了我自己的url....
![image](https://user-images.githubusercontent.com/20512530/82659810-e1a70d80-9c5b-11ea-8abc-3b2c1e54ac52.png)

**Comment by tangg555** [comment]
现在可用了！因为html转markdown格式有点问题，需要细调，谢谢大佬的热心帮助:-)。

**Comment by GinkgoX** [comment]
大佬好，https://blog.csdn.net/qq_37172182请问可以试试这个能下载吗？我的报错了：
/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:31
            throw new Error('invalid type');
                  ^

Error: invalid type
    at Object.<anonymous> (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:31:19)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:4:12)
    at Object.run (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:16:12)
    at /usr/local/lib/node_modules/csdnsynchexo/dist/cli.js:48:18
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/csdnsynchexo/dist/cli.js:9:71
    at new Promise (<anonymous>)

**Comment by flytam** [comment]
> 大佬好，[https://blog.csdn.net/qq_37172182请问可以试试这个能下载吗？我的报错了：](https://blog.csdn.net/qq_37172182%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E8%AF%95%E8%AF%95%E8%BF%99%E4%B8%AA%E8%83%BD%E4%B8%8B%E8%BD%BD%E5%90%97%EF%BC%9F%E6%88%91%E7%9A%84%E6%8A%A5%E9%94%99%E4%BA%86%EF%BC%9A) /usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:31 throw new Error('invalid type'); ^
> 
> Error: invalid type at Object. (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:31:19) at Generator.next () at /usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:8:71 at new Promise () at __awaiter (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:4:12) at Object.run (/usr/local/lib/node_modules/csdnsynchexo/dist/core/index.js:16:12) at /usr/local/lib/node_modules/csdnsynchexo/dist/cli.js:48:18 at Generator.next () at /usr/local/lib/node_modules/csdnsynchexo/dist/cli.js:9:71 at new Promise ()

npx csdnsynchexo@latest --type csdn --output ./example --userId qq_37172182
应该是type错了，试试呢

**Comment by Wang-0122** [comment]
`E:\gitee\CsdnSyncHexo\node_modules\csdnsynchexo\dist\core\index.js:32
            throw new Error(`invalid type: ${param.type}, Please check`);
                  ^

Error: invalid type: csdn, Please check
    at Object.<anonymous> (E:\gitee\CsdnSyncHexo\node_modules\csdnsynchexo\dist\core\index.js:32:19)
    at Generator.next (<anonymous>)
    at fulfilled (E:\gitee\CsdnSyncHexo\node_modules\csdnsynchexo\dist\core\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

`
也是这个报错了

我执行的命令
`npx csdnsynchexo@latest --type csdn --output ./example --userId SpringHASh`

已经是最新版本了
`npm i -g csdnsynchexo@latest`

我的csdn
[https://blog.csdn.net/SpringHASh](url)

有劳大佬帮忙看下！

**Comment by flytam** [comment]
windows电脑不太确定额，试试用双引号把csdn包起来呢。我mac试了下是ok的

**Comment by Wang-0122** [comment]
Hello tanjiahui

        还想请教一个问题，原csdn博客的内容中有图片的，我试着导出了一份md文件，放入hexo的source目录下，从hexo访问却无法显示图片，这是csdn对图床做了手脚吗？

Thanks
Wang



***@***.***
 
发件人： tanjiahui
发送时间： 2023-12-08 22:17
收件人： flytam/CsdnSyncHexo
抄送： wang; Comment
主题： Re: [flytam/CsdnSyncHexo] csdn的api更换了，并且新的api直接访问不返回结果 (#14)
windows电脑不太确定额，试试用双引号把csdn包起来呢。我mac试了下是ok的

**Comment by Wang-0122** [comment]
F:\gitee\CsdnSyncHexo>npx csdnsynchexo@latest --type "csdn" --output ./example --userId SpringHASh
版本 3.2.3
运行配置：
output ./example
userId SpringHASh
type csdn


(node:23056) UnhandledPromiseRejectionWarning: Error: invalid type: csdn, Please check
    at Object.<anonymous> (C:\Users\wangyao\AppData\Roaming\npm-cache\_npx\23056\node_modules\csdnsynchexo\dist\core\index.js:32:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\wangyao\AppData\Roaming\npm-cache\_npx\23056\node_modules\csdnsynchexo\dist\core\index.js:5:58)
(node:23056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



我尝试了加 单引号''、双引号""  
还是不行 T_T
