### ISSUE TITLE
有没有你编译好的能直接运行的 我没有node环境

### ISSUE THREAD

**Issue by ghost** [flytam/CsdnSyncHexo#16]
本来是求个不用自己安装node环境的编译好的包的，但是我等不及了，安装了个环境运行时出现了一下问题：
![image](https://user-images.githubusercontent.com/23163284/88358459-a337e700-cda1-11ea-8e7b-54271a0aa10e.png)
部分文章是可以正常下载的，下载正常的看起来挺完美的。
有一些运行时直接报错了，

```
出错: 103756139 { FetchError: request to https://blog.csdn.net/ThinkWon/article/details/103756139 failed, reason: socket hang up
    at ClientRequest.<anonymous> (E:\Program Files\nodejs\node_gobal\node_modules\csdnsynchexo\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketOnEnd (_http_client.js:426:9)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://blog.csdn.net/ThinkWon/article/details/103756139 failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```
操作系统 ： windows10
niode版本： v10.16.3
下载目录地址 " ./新建文件夹/
配置文件 ：
```
{
  "csdn": "https://blog.csdn.net/ThinkWon",
  "output": "./ThinkWon"
}
```

**Comment by flytam** [comment]
@a13087635768 试下使用cookie的呢？

**Comment by flytam** [comment]
@a13087635768 修复了一些bug.`npm i -g csdnsynchexo@latest`安装下最新版再尝试下即可。我用你的配置试过ok的。
![image](https://user-images.githubusercontent.com/20512530/88386841-cc796700-cde3-11ea-96a0-0f2c711bedb0.png)

ps: 如果好用，你的star是我最大的动力～

**Comment by ghost** [comment]
> @a13087635768 修复了一些bug.`npm i -g csdnsynchexo@latest`安装下最新版再尝试下即可。我用你的配置试过ok的。
> ![image](https://user-images.githubusercontent.com/20512530/88386841-cc796700-cde3-11ea-96a0-0f2c711bedb0.png)
> 
> ps: 如果好用，你的star是我最大的动力～

那必须 star
