### ISSUE TITLE
好像接口出问题了？

### ISSUE THREAD

**Issue by godzeo** [flytam/CsdnSyncHexo#17]
好像接口出问题了？带上cookie 也不行了，没数据了
![image](https://user-images.githubusercontent.com/64398024/89029448-0d7ff700-d361-11ea-90c2-07bd6ddfa9b2.png)

**Comment by flytam** [comment]
目前最新版本2.2.3.`npm i -g csdnsynchexo@latest`按照下最新版试试

**Comment by godzeo** [comment]
还是不行，不清楚啥情况，csdn地址也检查了，不知道哪里出问题了

**Comment by flytam** [comment]
发下你的配置文件我看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: godzeo <notifications@github.com&gt;
发送时间: 2020年7月31日 22:56
收件人: flytam/CsdnSyncHexo <CsdnSyncHexo@noreply.github.com&gt;
抄送: Flytam <tanjiahui2015@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[flytam/CsdnSyncHexo] 好像接口出问题了？ (#17)





 
还是不行，不清楚啥情况，csdn地址也检查了，不知道哪里出问题了

**Comment by godzeo** [comment]
{
  "csdn": "https://blog.csdn.net/god_zzZ",
  "output": "/Users/zy/Documents/blog/source/_posts"
}

**Comment by flytam** [comment]
已修复。csdn最近页面有变更`npm i -g csdnsynchexo@latest`安装最新版即可

**Comment by godzeo** [comment]
我试了一下，还是不行。。。

**Comment by flytam** [comment]
![image](https://user-images.githubusercontent.com/20512530/89092610-cee05000-d3e5-11ea-9c9e-d574d56784c3.png)
可以呀

**Comment by godzeo** [comment]
我好像更新不了2.2.4 
我重新git clone 然后 sudo npm i -g csdnsynchexo@latest
![image](https://user-images.githubusercontent.com/64398024/89092934-7068a100-d3e8-11ea-85c7-0071a2061f2e.png)

![image](https://user-images.githubusercontent.com/64398024/89092729-e409ae80-d3e6-11ea-91f1-32e60a76d077.png)

**Comment by godzeo** [comment]
好了，库更新了，到2.2.4了
