### ISSUE TITLE
安装成功后，我居然不会用……

### ISSUE THREAD

**Issue by yansheng836** [flytam/CsdnSyncHexo#2]
因为没有接触过Node.js，所以看不懂代码，只能跟着README走，但是频频出错……（个人感觉是：README好像有点太简单了，不太适合我这种小白:joy:）

具体问题分析（Windows10）：

### 1. 命令行指定运行（3个参数）
按照提示加了三个参数：--output，--csdn，--cookies，然后报错了：`error: unknown option `--cookies'`,然后我以为是cookies里面有空格，然后加了单引号--无效，又加了双引号--还是无效，有点绝望……

最后突然想起：好像没有这个参数，但是README好像没更新这部分文档，误导我了……
```bash
$ hsync -h
Usage: start [options]

Options:
  -V, --version          output the version number
  -c, --config [config]  配置文件相对路径
  -o, --output [output]  本地生成博客源md文件路径
  --csdn [csdn]          csdn博客地址
  -b,--base[base]        本地hexo根目录，不提供则不执行hexo d
  -h, --help             output usage information
```

### 2. 命令行指定运行（2个参数）
发现问题后，我开始用2个参数进行尝试：

报错了：
```bash
$ hsync --output ./blog/ --csdn https://blog.csdn.net/weixin_41287260
1.1.3版本 csdn -> hexo生成器
正在生成文件....
输出目录不存在，正在创建...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'G:\Git\git_repository\csdn-md\CsdnSyncHexo\blog\FastStone Capture 注册码\注册机.md'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

```

我去看了下，发现是标题名中含有文件名中的特殊字符，导致新建文件失败：

![image](https://user-images.githubusercontent.com/45334066/64337917-f599d900-d012-11e9-9a06-e7a299c0fef1.png)
---

原博客标题信息：
![image](https://user-images.githubusercontent.com/45334066/64338011-30037600-d013-11e9-9964-ec853a16dd1f.png)

文件名规则：
![文件名规则](https://img-blog.csdn.net/20180331142340771)

虽然文件名有一定要求，但是文章标题好像没什么要求吧（不能太长好像不算……），因此总不能要求别人要如何命名文章标题吧？其实最简单的就是替换违规字符，可参考这篇文章：[java替换文件名字符串中的特殊字符，使其能成功创建文件](https://blog.csdn.net/weixin_41287260/article/details/99255567)，虽然每次都要检测会比较费时，但是对于计算机而言这点花费好像不算什么。

### 3. 配置文件运行

这部分没看懂，我尝试着找了下配置文件，好像没有找到有类似参数的文件；然后我就自己新建了一个txt文本文件，填入对于的参数。

额，还是报错了：
```bash
# 1.一开始尝试相对路径
$ node ./start.js ./csdn_hexo_config.txt
1.1.3版本 csdn -> hexo生成器
请指定配置文件路径
(node:3000) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\yansheng\AppData\Roaming\npm\node_modules\csdnsynch
exo\node_modules\node-fetch\lib\index.js:1299:9)

#2.后面我尝试绝对路径
$ node ./start.js ‪C:\Users\yansheng\AppData\Roaming\npm\node_modules\csdnsynchexo\dist\csdn_hexo_config.txt
1.1.3版本 csdn -> hexo生成器
请指定配置文件路径
(node:16064) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported

# 3.再后来我以为是Windows和Linux的路径分隔符不同造成的，又试了下：
$ node ./start.js ‪/C:/Users/yansheng/AppData/Roaming/npm/node_modules/csdnsynchexo/dist/csdn_hexo_config.txt
1.1.3版本 csdn -> hexo生成器
请指定配置文件路径
(node:3160) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported

# 4. 没有4了，我也不知道咋回事……，猜测是Windows有盘符，Linux没有……
```

**Comment by yansheng836** [comment]
还有就是在下载时，感觉用户体验不是很好，建议转换成功一篇文章就输出其文件名；要不是我去看文件夹，都不知道有下载成功的文章……

**Comment by flytam** [comment]
辛苦老哥。。最后你是生成成功了吗

**Comment by flytam** [comment]
配置文件应该是要使用js作为配置文件的.

**Comment by yansheng836** [comment]
没有呢，我又发了个issue #3

**Comment by yansheng836** [comment]
感谢 @flytam 解决了我的问题，亲测该issue提到的两种运行方法都能够正常运行，为了关闭这个issue，重复一下使用方法（适合真正的小白:smile:）：

### 0. 前期准备：
- 安装Node.js
- 安装npm，npm 是JavaScript 世界的包管理工具，并且是Node.js 平台的默认包管理工具。通过npm 可以安装、共享、分发代码，管理项目依赖关系。
- 全局安装 `csdnsynchexo`工具包，命令行运行：`npm i -g csdnsynchexo`
- 将本项目代码克隆到本地，`git clone https://github.com/flytam/CsdnSyncHexo.git`

### 方法1：配置文件运行 （推荐）
1.1 先配置`CsdnSyncHexo/config.json`文件，修改里面的对应信息，
```json
// config.json
{
  "csdn": "https://blog.csdn.net/flytam", // csdn博客地址
  "output": "./example", // 这里可以定向到你的hexo源文件的地方
  "cookies": "xxxx", // cookie
  "base": "可选" // hexo博客源文件目录，用于执行hexo命令
}
```

1.2 运行命令（会扫描刚配置的文件，获取到命令中需要的参数）:`hsync --config ./config.json`


### 方法2：直接使用命令行运行
在此之前你需要准备好几个参数，具体可见README，需要注意的是`--cookies`选项的参数要加上引号，因为你复制的cookies可能会有空格等字符，可能会被截断。

```bash
hsync --output /Users/flytam/Desktop/coding/blog/source/_posts --base /Users/flytam/Desktop/coding/blog --csdn https://blog.csdn.net/flytam --cookies "your_cookies_info"
```
