### ISSUE TITLE
使用配置文件方式爬取，返回的网址是xxxxx/article/list/2

### ISSUE THREAD

**Issue by JingYu0266** [flytam/CsdnSyncHexo#22]
是对csdn博客爬取的，在配置文件放入userId,type,output,cookie后， 启用成功，但提示request: get https://blog.csdn.net/xxxxxxxx/article/list/2 
下面是我放的配置文件：
{
        "userId": "qq_40454401",
        "type": "csdn",
        "output": "./example",

提供cookie，使用文章api获取模式
输出路径 /...../...../...../..../example

**Comment by flytam** [comment]
@JingYu0266 有点bug，已经修复发布了3.0.4版本了。`npm i csdnsynchexo@latest `使用最新版可以了，另外请不要贴cookie上来。。有风险
