### ISSUE TITLE
转化的文章有问题

### ISSUE THREAD

**Issue by yansheng836** [flytam/CsdnSyncHexo#3]
转换的文章存在问题：文章不是只有头部信息，就是空白（下载了26个文件，只有2个文件是完整），这个问题很致命！！

部分截图：

只有头部信息的：
![image](https://user-images.githubusercontent.com/45334066/64339488-c2594900-d016-11e9-86b0-503518153002.png)

---
几乎空白的：
![image](https://user-images.githubusercontent.com/45334066/64339685-22e88600-d017-11e9-9651-79a97d60ac35.png)

### 个人分析（猜测）
1. 因为仓库新建已有一段时间，csdn博客界面元素有所变化，可能是取不到原有元素。这个问题比较常见，不要问我为什么知道，因为我找的多了就知道了（可是我找了这么久CSDN-->HEXO，都没有满意的……找到的都有大大小小各种各样的问题）。

2. CSDN编辑器原因：因为CSDN有两种编辑器：富文本编辑器和markdown编辑器，这两种编辑器编辑的文章的页面的元素会略有区别（我之前爬CSDN就遇到过这个坑）：
![image](https://user-images.githubusercontent.com/45334066/64340255-4829c400-d018-11e9-9a46-ee789bacdde1.png)

详细可参考：<https://blog.csdn.net/weixin_41287260/article/details/99237875#2__279>。

**Comment by flytam** [comment]
@yansheng836  感谢反馈。我周末搞搞看

**Comment by yansheng836** [comment]
个人分析仅供参考，全是经验之谈，毕竟看不太懂代码:smile:。

**Comment by flytam** [comment]
@yansheng836 我试了下 能成功呀。我更新了文档和版本了，最新版会输出文章名字。可以看看文档指定配置文件那种方法，配置文件时json

**Comment by flytam** [comment]
@yansheng836 更新到2.0.4版本即可完美解决，已经修复了你说的问题了。文档增加了说明，可以使用配置文件运行那种方法。我测试过ok了。你可以时下

**Comment by yansheng836** [comment]
虽然有所改进，但是好像还是有问题，我把我信息发给你，麻烦你帮忙试下：

**Comment by yansheng836** [comment]
```json
{
  "csdn": "https://blog.csdn.net/weixin_41287260",
  "output": "./example",
  "cookies": "uuid_tt_dd=10_37481511700-1561569334879-573464; smidV2=201905281430271e27062c523c515f3b596a96a841e9ba003e36e178c04bae0; UN=weixin_41287260; __yadk_uid=ZHHdL1XvKl7VllGV4dk1ofXfOytbpH6B; bdshare_firstime=1563175305477; dc_session_id=10_1563367037090.145835; UserName=weixin_41287260; UserInfo=073cba9817f641f4a180c83b352c6511; UserToken=073cba9817f641f4a180c83b352c6511; UserNick=%E7%A7%A6%E6%97%B6%E6%98%8E%E6%9C%88%E4%B9%8B%E5%90%9B%E4%B8%B4%E5%A4%A9%E4%B8%8B; AU=6CE; BT=1565254864534; p_uid=U000000; firstDie=1; TINGYUN_DATA=%7B%22id%22%3A%22-sf2Cni530g%23HL5wvli0FZI%22%2C%22n%22%3A%22WebAction%2FCI%2FarticleList%252Flist%22%2C%22tid%22%3A%22e63b88e91f9e00%22%2C%22q%22%3A0%2C%22a%22%3A66%7D; c_adb=1; dc_tos=pxd8t1"
}

```

**Comment by flytam** [comment]
@yansheng836 我等下试下。。不过你的cookie别直接贴出来呀兄弟。我用我自己的cookie就行了

**Comment by flytam** [comment]
![图片](https://user-images.githubusercontent.com/20512530/64402164-77871200-d0a6-11e9-80f6-cdf1312bccef.png)
我这边爬出来正常啊，有什么问题吗？ 
如果是富文本的文章，是html
markdown的文章则是markdown

**Comment by yansheng836** [comment]
弱弱的问下：要怎么更新啊？
git pull
npm update csdnsynchexo

这个对吗？

**Comment by flytam** [comment]
@yansheng836  
npm i -g csdnsynchexo
然后按照文档运行，运行的时候会有版本号输出的
![图片](https://user-images.githubusercontent.com/20512530/64405854-db173c80-d0b2-11e9-9f7e-ba852d5b248c.png)

**Comment by yansheng836** [comment]
果然是没有更新成功的问题；之前我以为更新成功了，但是奇怪为什么执行命令还是显示：“1.1.3版本”，但是json版本信息里面确是2.0.4版本了。

还有就是感觉npm工具好像不太好用，我运行“npm update csdnsynchexo”命令居然没有什么输出，即没报错，也没有任何提示信息；我之前看过一篇文章（好像是Linux还是Git相关的）说：“，命令行没有显示信息，就是好情况”……，但是这里的，把我搞蒙了。

然后“npm uninstall csdnsynchexo”也啥反应，hsync命令照样运行……

而且没想到已安装的包居然可以再次`npm i `，我感觉有点反人类了:joy:，感觉没有python的pip工具和Windows的git好用。

---

总之，不管怎么吐槽npm(也可能是我太菜了……:grinning:)；还是得感谢大佬的耐心回答，可以实现转换了，优点：**1. 关于命令行：用户体验比较好了，转换成功有提示（即使它很快就生成了，但是最起码你可以知道哪篇文章转换成功了）。2. 可以成功新建md文件（即使csdn博客标题可能含有违规字符）。3.没有乱码，内容也完整**，不过好像还有一点点瑕疵（个别标签有问题，等我研究清楚再反馈下吧），非常牛逼。

**Comment by flytam** [comment]
标签问题。我再看看，哈哈。求一个star呀

**Comment by yansheng836** [comment]
自从我想实现CSDN转HEXO(或者说是markdown)，前后找了很多工具，应该不下10个了，有python的（python居多）、有java的、有node.js的，但是能够成功转换的压根就没有几个！！！不是环境不符合要求、就是工具本身存在问题（年久失修？！）；再者就是即使能够转换，转换的hexo博客的优化也不够好，和原csdn博客有较大差距。

没想到找个好用的“轮子”居然这么难，（放张最近很热的图）
![我太难了](http://wx3.sinaimg.cn/bmiddle/006GJQvhgy1g5qgg8yg1zj30u00ncwfz.jpg)

还好找遇见你（不，是遇见了这个项目）！毫不夸张地说：**这个工具是我用过的最好的CSDN转HEXO的工具**，话不多说，点个赞以表谢意:+1:。

**Comment by yansheng836** [comment]
额，居然没有star，是我疏忽了:grin:
