### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by tuyile-icu** [flytam/CsdnSyncHexo#43]
![image](https://user-images.githubusercontent.com/93823931/235286528-8098d721-5ee0-4b96-a2fd-36fb189ae91c.png)

**Comment by flytam** [comment]
可以重新试一下

**Comment by tuyile-icu** [comment]
还是不行，甚至连你的都下不了
npx csdnsynchexo@latest --userId m0_67563237 --type CSDN --output ./_posts
可以帮我试一下吗😭😭

**Comment by flytam** [comment]
我试了你的可以呀，csdn小写。。截图看看？
<img width="652" alt="image" src="https://user-images.githubusercontent.com/20512530/235334867-2d079ead-7abd-432f-8e8f-a74bd4835827.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/20512530/235334870-eea3c340-3ce6-41b1-b9db-2c8e6b7c8dd2.png">

**Comment by tuyile-icu** [comment]
![image](https://user-images.githubusercontent.com/93823931/235335488-f802268f-39fb-460d-a041-eff08a08fee5.png)
小写也不行丫😭😭，实在不行可以发给我吗 3189248615@qq.com ，非常感谢大佬

**Comment by flytam** [comment]
怎么感觉你的版本不是最新的，最新版会打印版本号的

**Comment by tuyile-icu** [comment]
还是不行啊😭😭  npx csdnsynchexo@latest --userId m0_67563237 --type csdn --output ./_posts
![image](https://user-images.githubusercontent.com/93823931/235362203-cf42290c-c543-47b4-a821-0676f9ff1cbe.png)
你试一下能用能发给我吗

**Comment by flytam** [comment]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/20512530/235396721-244a5eb2-1f30-47e5-b462-1d3e2af0c177.png">
已经发了，不如也顺手给我个star哈哈

**Comment by flytam** [comment]
可能是因为windows有一些奇怪的兼容问题，我没有windows暂时试不了。。

**Comment by tuyile-icu** [comment]
非常非常感谢，给我狠狠的starstarstar😍😍😍😍
