### ISSUE TITLE
invalid type

### ISSUE THREAD

**Issue by tossorrow** [flytam/CsdnSyncHexo#49]
![image](https://github.com/user-attachments/assets/91a33903-5b22-4019-9047-9c06033dd543)
各种type都尝试过了（比如csdn，bokeyuan，cnblogs），都报错invalid type。

**Comment by zhywzs** [comment]
我在linux下的报错是这样的，我使用bokeyuan，此问题已被解决：
```bash
/root/.npm/_npx/19f9ba3a482e8930/node_modules/csdnsynchexo/dist/extension/bokeyuan/index.js:69
                const $ = cheerio_1.default.load(html);
                                            ^

TypeError: Cannot read properties of undefined (reading 'load')
```
vim /root/.npm/_npx/19f9ba3a482e8930/node_modules/csdnsynchexo/dist/extension/bokeyuan/index.js
找到两处
```js
const $ = cheerio_1.default.load(html);
// 修改为：
const $ = cheerio_1.load(html);
```
你如果使用其他的网站，需要修改对应的部分。但是都在`csdnsynchexo/dist/extension`下。
我的环境如下：
```bash
root@haxo:~/cnblogs/example# npx -v
10.8.2
root@haxo:~/cnblogs/example# npm -v
10.8.2
root@haxo:~/cnblogs/example# npx csdnsynchexo@latest -V
3.2.3
```
希望对你有用。我只测试了博客园的代码。

**Comment by flytam** [comment]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/97b21285-e1d9-42da-bdb0-a78ab45f3980">
我这里好像无法复现。node 20

**Comment by zhywzs** [comment]
能否提供`npx csdnsynchexo@latest -V`的运行结果？

**Comment by flytam** [comment]
10.8.2。cheerio那个报错和npx版本应该无关。感觉是代码依赖中引用的cheerio是一个es模块

**Comment by flytam** [comment]
npx csdnsynchexo@beta ...
发了个beta的改成es实现，可以试试

**Comment by flytam** [comment]
npx csdnsynchexo@latest ... 执行应该可以了，把代码更新成esmodule的形式
